config/routes.rb
Bae::Application.routes.draw do
  get "/login" => "login#new", :as =>"login"
  post "/login" => "login#create"

  match "/logout" => "login#destory", :as=>"logout"
  match "/:room" => "login#today"

  match "/freebusy/:room/:date" => "book#index", :as => "freebusy"
  match "/book/confirm" => "book#confirm", :as => "book_confirm"
  get "/book/:room/:from/:to" => "book#create", :as => "book"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :is_login
  #around_filter :set_timezone

  def set_timezone
    Time.use_zone('Beijing') do
      yield
    end
  end


  def is_login
    unless cookies[:username] && cookies[:password] 
      redirect_to login_path + "?redirect=%s" % request.fullpath
    end
  end

  def server_query(param)
    require 'open-uri'
    param[:user] = cookies[:username]
    param[:pwd] = cookies[:password]
    param[:room] = param[:room] + "@ef.com"
    
    log = Logger.new(STDOUT)
    begin
      url = "%s?%s" % [APP_CONFIG[:service_url], Rack::Utils.build_query(param)]
      log.info(url)
      ActiveSupport::JSON.decode(open(url).read)
    rescue
    end
  end

  def freebusy(room, from, to)
    param = {:action=>"freebusy", :room=>room, :from=>from.iso8601, :to=>to.iso8601}
    server_query(param)
  end

  def book(room, starttime, endtime, subject, body)
    param = {:action=>"book", :room=>room, :start=>starttime.iso8601, :end=>endtime.iso8601, :subject=>subject, :body=>body}
    server_query(param)
  end

  def cancel(room, starttime, endtime, subject, body)
    param = {:action=>"cancel", :room=>room, :start=>starttime.iso8601, :end=>endtime.iso8601, :subject=>subject, :body=>""}
    server_query(param)
  end
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  def index
    respond_to do |format|
      @df = DateTime.parse(params[:date])
      @dt = @df + 1.day
      @room = params[:room]
      
      list = freebusy(@room, @df, @dt)
      @clist = []

      if list.kind_of?(Array)
        lastEnd = @df
        (0..(list.count-1)).each do |i|
          c = list[i]
          c["StartTime"] = DateTime.parse(c["StartTime"])
          c["EndTime"] = DateTime.parse(c["EndTime"])
          next if c["StartTime"] < @df
           
          if c["StartTime"] > lastEnd 
            cnew = {"StartTime"=>lastEnd, "EndTime"=>c["StartTime"], "FreeBusyStatus"=>0}
            @clist << cnew
          end
          @clist << c
          lastEnd = c["EndTime"]
        end

        if @dt > lastEnd 
          cnew = {"StartTime"=>lastEnd, "EndTime"=>@dt, "FreeBusyStatus"=>0}
          @clist << cnew
        end
      end

      namehash = {
        'cnshhq-conf01' => "1F, Cape Town",
        'cnshhq-conf02' => "1F Casablanca",
        'cnshhq-conf03' => "1F Dakar",
        'cnshhq-conf18' => "1F Stadium",
        'cnshhq-conf35' => "2F Amsterdam",
        'cnshhq-conf19' => "2F Dublin",
        'cnshhq-conf06' => "2F London",
        'cnshhq-conf07' => "2F lucerne",
        'cnshhq-conf22' => "2F Moscow",
        'cnshhq-conf23' => "2F Paris",
        'cnshhq-conf20' => "2F Rome",
        'cnshhq-conf08' => "2F Stockholm",
        'cnshhq-conf09' => "2F Zurich"
      }

      @name = namehash[@room.downcase]
      @daylist  = []
      0.upto(7) do |i|
        @daylist << (@df + i.day)
      end


      format.html
    end
  end

  def create
    @df = DateTime.parse(params[:from])
    @dt = DateTime.parse(params[:to])
    @room = params[:room]

    @clist = []
    tstart = @df.change(:min=>(@df.minute/15.0).ceil * 15)
    while tstart < @dt do
      @clist << tstart
      tstart += 15.minutes
    end

    respond_to do |format|
      format.html
    end
  end
  
  def confirm
    @df = DateTime.parse(params[:starttime])
    @dt = DateTime.parse(params[:endtime])
    book(params[:room], @df, @dt, params[:subject], "")
    flash[:notice] = "Your request has been sent"
    redirect_to freebusy_path(:date=>@df.strftime("%Y-%m-%d"), :room=>params[:room])
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  skip_filter :is_login
  def new
    respond_to do |format|
      format.html
    end
  end

  def today
    redirect_to freebusy_path(:date=>DateTime.now.midnight.iso8601, :room=>params[:room])
  end

  def create
    username = params[:username]
    password = params[:password]
    if username && password
      expires = 2.week.from_now
      cookies[:username] = {:value=>username, :expires=>expires}
      cookies[:password] = {:value=>password, :expires=>expires}
      flash[:notice] = "Logged in"
      
      redirect_to params[:redirect]
    end
  end

  def destory
    cookies.delete :username
    cookies.delete :password
    redirect_to login_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/book/create.html.erb
<%= form_tag(book_confirm_path) do %>
  From:
  <br/>
  <%= select_tag :starttime, options_for_select(@clist.map{|c| [c.strftime('%H:%M'), c]}) %>
  <br/>
  To:  
  <br/>
  <%= select_tag :endtime, options_for_select(@clist.map{|c| [c.strftime('%H:%M'), c]}) %>
  <br/>
  <%= hidden_field_tag :room, @room %>
  Subject:
  <br/>
  <%= text_field_tag :subject %>
  <br/>
  <%= submit_tag "Book", :class=>"btn btn-success" %>
<%end%>
<% content_for :title do %>
  Book
<%end%>

app/views/book/index.html.erb
<div>
  <%= select_tag :date, options_for_select(@daylist.map{|d| [d.strftime("%Y-%m-%d (%a)"), d]})%>
</div>
<hr/>
<% @clist.each do |c| %>
  <% if c["FreeBusyStatus"] == 0 %>
    <div class="well alert alert-success timecell">
      Bookable: <%= c["StartTime"].strftime('%H:%M') %> to <%= c["EndTime"].strftime('%H:%M') %>
      <%= link_to "Book", book_path(:room=>@room, :from=>c["StartTime"], :to=>c["EndTime"]), :class=>"btn btn-success pull-right" %>
    </div>
  <% else %>
    <div class="well timecell">
      <%= c["Owner"] || "Occupied" %>, <%= c["StartTime"].strftime('%H:%M') %> to <%= c["EndTime"].strftime('%H:%M') %>
      <% if c["Owner"] && c["Owner"].downcase == cookies[:username].downcase %>
        <%= link_to "X", "#", :class=>"btn btn-danger pull-right" %>
      <%end%>
    </div>
  <% end %>
  
<% end %>
<% content_for :bottom_js do%>
  <script>
    $(document).ready(function(){
      $('#date').change(function(){
        var p = "<%= freebusy_path(:date=>"", :room=>params[:room]) %>";
        window.location = p + $(this).val();
      })
    })
  </script>
<%end%>
<% content_for :title do %>
  <%= @name %>
<%end%>
<% content_for :head_css do %>
  <style>
.timecell{min-height:30px;}
  </style>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="initial-scale=1.0">
    <title></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'http://lib.sinaapp.com/js/bootstrap/2.2.1/css/bootstrap.min.css', 
      'application', 
      "http://lib.sinaapp.com/js/bootstrap/2.2.1/css/bootstrap-responsive.min.css", :media => "all" %>
    <%= yield(:head_css) if content_for?(:head_css) %>
  <style>
      @media (min-width: 1200px) {
        body{padding-top:60px;}
      }

      .brand
      {
          position: absolute;
          width: 100%;
          left: 0;
          text-align: center;
          margin: auto;
      }
  </style>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
          <div class="brand">
            <%= content_for :title if content_for :title %>
          </div>
          <ul class="nav">
            <li>
            <%= link_to "Logout", logout_path %>
            </li>
          </ul>
      </div>
    </div>

    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-block alert-success">
        <%= flash[:notice] %>
      </div>
      <% end %>
      <% if flash[:error] %>
          <div class="alert alert-block alert-error">
          <%= flash[:error] %>
        </div>
      <% end %>
    </div>

    <% if content_for?(:root_highlight) %>
    <div class="root-highlight">
      <div class="container">
      <%= yield(:root_highlight) %>
      </div>
    </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div> <!-- /container -->
    
    <div class="footer">
    <hr/>
    <div class="container" style="padding-bottom:10px">
      <footer>
        &copy;2013 EF Labs
      </footer>
    </div> <!-- /container -->
  </div> <!-- end of footer -->
    <%= javascript_include_tag 'http://lib.sinaapp.com/js/jquery/1.9.0/jquery.min.js', 'http://lib.sinaapp.com/js/bootstrap/2.2.1/js/bootstrap.min.js', 'application' %>
    <%= yield(:bottom_js) if content_for?(:bottom_js) %>
  </body>
</html>

app/views/login/new.html.erb
<%= form_tag do %>
  <p><%= text_field_tag :username, "", :placeholder=>"Username" %></p>
  <p><%= password_field_tag :password, "", :placeholder=>"Password" %></p>
  <p><%= submit_tag "Login", :class=>"btn btn-primary" %></p>
  <%= hidden_field_tag :redirect, params[:redirect] %>
<% end %>
<% content_for :title do %>
  Login
<% end %>